#!/usr/bin/env bash
# This script tranfers a file from a client to a server
if [ '$#' < 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
if [ $? -eq 0 ];
then
	echo "File transferred successfully to $USERNAME@$IP:~/"
else
	echo "File transfer failed"
fi
