#!/usr/bin/env bash
# This script confiugures a server web02 to interact with web01
if ! command -v nginx > /dev/null 2>&1; then
	sudo apt-get update
	sudo apt-get install -y nginx
	ufw allow "Nginx HTTP"
fi

HOST_NAME=$(hostname)

NGINX_CONF="/etc/nginx/sites-available/default"

if [ ! -f "$NGINX_CONF.bak" ]; then
	sudo cp "$NGINX_CONF" "$NGINX_CONF.bak"
fi

sudo sed -i '/^ *server *{/,/^ *}$/s/^\( *server *{\)/\1\n    add_header X-Served-By '"$HOST_NAME"';/' "$NGINX_CONF"

sudo service nginx start

echo "X-Served-By: $HOST_NAME"
