#!/usr/bin/env bash
# This script creates a file containing its PID, displays a sentence indefinitely, and receives different kill signals.
echo $$ > /var/run/myscript.pid
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT SIGTERM
handle_sigterm() {
	echo "I hate the kill command"
	exit 0
}
handle_sigint() {
	echo "Y U no love me?!"
	exit 0
}
handle_sigquit() {
	rm -f '/var/run/myscript.pid'
	exit 0
}
while true
do
	echo "To infinity and beyond"
	sleep 2
done
