#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely, with a sleep 2 in betwwen iteration, I am invincible!!! when receiving a SIGTERM signal.
while true
do
	echo "To infinity and beyond"
	sleep 2
done
trap 'I am invincible!!!' SIGTERM
