#!/usr/bin/env bash
# This script displays FizzBuzz when a number is a multiple of 3 and 5, Fizz when the number is a multiple of 3, Buzz when it is a multiple of 5, otherwise displays the number.
for i in {1..100}
do
	if (( i % 3 == 0 && i % 5 == 0))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
