#!/usr/bin/env bash
# This script uses awk command to display the visitor IP along with the HTTP status code from the Apache log file.
awk '{print $1, $9}' /mnt/c/Users/Adime/Downloads/apache-access.log
