#!/usr/bin/env bash
# This script prints "Best School" 10 times but on the 9th iteration it displays hi on a new line.
counter=0
while [ $counter -lt 10 ]
do
	if [ $counter = 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
