#!/usr/bin/env bash
# This script configures an Ubuntu server.
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/g' /etc/hosts
sudo sed -i 's/108.132.101.35 facebook.com/8.8.8.8 facebook.com/g' /etc/hosts
